### ISSUE TITLE
cpu hotplug-unplug in parallel with suspend resume.. guest becomes unresponsive..

### ISSUE THREAD

**Issue by bssrikanth** [open-power-host-os/linux#16]
I tried cpu hotplug-unplug in parallel with suspend resume.. guest becomes unresponsive..
i. On host run
terminal 1:
     for i in {1..100};do sleep 2;virsh suspend srikanth_1710_Cdrom;sleep 2;virsh resume srikanth_1710_Cdrom;done
terminal 2:
     for i in {1..100};do sleep 5;virsh setvcpus srikanth_1710_Cdrom 4 --live;sleep 5;virsh setvcpus srikanth_1710_Cdrom 2 --live;done

ii. After/while both above commands complete, will start seeing below messages on guest console:

[ 1209.368538] INFO: task jbd2/dm-0-8:1088 blocked for more than 120 seconds.
[ 1209.368633]       Not tainted 4.12.0-11-generic #12-Ubuntu
[ 1209.368694] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.

And the guest goes unresponsive.. 

I could'nt run sosreport on guest since it was unresponsive.. 

I tested same scenario as mentioned in previous comment with latest hostos guest.. I am hitting similar stall issues there as well...
I am attaching the traces of hostos here..
Guest is hung.. so could not get sosreports...

So these stall issues present on Ubuntu 17.10 [kernel: 4.13.0-11] and HostOS guest [kernel: 4.13.0-4.rel ]

In an internal comment I will post machine access details and guest details..

<cde:info> Mirrored with LTC bug #159338 </cde:info>

**Comment by bssrikanth** [comment]
[Stall_hostosguest.txt](https://github.com/open-power-host-os/linux/files/1336080/Stall_hostosguest.txt)

**Comment by bssrikanth** [comment]
@Sam has fix for this issue, patch @ http://www.spinics.net/lists/kvm-ppc/msg12981.html ..
This bug is track verification of the issue when HostOS gets the above patch

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2017-12-04 04:54:15 EDT-------
Tested on 4.14 rel branch.. issue seems to be fixed from the tests conducted. Closing.
