### ISSUE TITLE
kdump service not starting with crashkernel=auto

### ISSUE THREAD

**Issue by bssrikanth** [open-power-host-os/linux#28]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=164225 </cde:info>

crashkernel with auto:

dmesg | grep crash
[    0.000000] crashkernel: memory value expected
[    0.000000] Kernel command line: root=/dev/mapper/host_os_ltc--wspoon5-root ro crashkernel=auto console=tty0 rd.lvm.lv=host_os_ltc-wspoon5/root rd.lvm.lv=host_os_ltc-wspoon5/swap

crashkernel with explicit value:
[root@ltc-wspoon5 ~]# dmesg | grep -i crash
[    0.000000] Reserving 256MB of memory at 128MB for crashkernel (System RAM: 524288MB)
[    0.000000] Kernel command line: root=/dev/mapper/host_os_ltc--wspoon5-root ro crashkernel=256M console=tty0 rd.lvm.lv=host_os_ltc-wspoon5/root rd.lvm.lv=host_os_ltc-wspoon5/swap

**Comment by cdeadmin** [comment]
------- Comment (attachment only) From bssrikanth@in.ibm.com 2018-02-03 03:01:01 EDT-------

**Comment by cdeadmin** [comment]
------- Comment From muriloo@br.ibm.com 2018-02-05 08:39:55 EDT-------
The crashkernel=auto syntax is specific to RHEL kernels. The upstream kernels (including HostOS) don't accept this syntax and a numeric value is expected. To learn more about kdump syntax, check http://elixir.free-electrons.com/linux/v4.15/source/Documentation/kdump/kdump.txt.

For me, this is working as designed and it's not a bug.
