### ISSUE TITLE
 Out-of-tree kernel modules fail to build on hostos

### ISSUE THREAD

**Issue by bssrikanth** [open-power-host-os/linux#34]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=169899 </cde:info>

kernel-devel package does not seem to contain arch/powerpc/kernel/module.lds.

Manually copying that file to said location resolve issue. But we need to include module.lds in kernel-devel..

Similar issue was as well reported in https://bugzilla.redhat.com/show_bug.cgi?id=1574604 and https://bugzilla.redhat.com/show_bug.cgi?id=1531182..

**Comment by farosas** [comment]
@bssrikanth next build should contain the `arch/powerpc/kernel/module.lds` file.
